name: 'Sync feedback comment'
description: 'Given a PR, "upsert" a comment with the given message'
inputs:
  pull_request_url:
    required: true
    description: 'Pull Request URL'
  message:
    required: true
    description: 'Markdown message'
runs:
  using: 'node16'
  main: 'dist/index.js'
